// Generated by CoffeeScript 1.7.1
(function() {
  var DecisionTree, Task;

  Task = (function() {
    Task.prototype.type = 'base-task';

    Task.prototype.key = '';

    Task.prototype.question = '';

    Task.prototype.choices = null;

    Task.prototype.next = null;

    Task.prototype.confirmLabel = 'OK';

    Task.prototype.template = function() {
      var choice, i;
      return "<div class='decision-tree-question'>" + this.question + "</div> <div class='decision-tree-choices'> " + (((function() {
        var _i, _len, _ref, _results;
        _ref = this.choices;
        _results = [];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          choice = _ref[i];
          _results.push("<div class='decision-tree-choice'>" + (this.choiceTemplate(choice, i)) + "</div>");
        }
        return _results;
      }).call(this)).join('\n')) + " </div> <div class='decision-tree-confirmation'> <button type='submit' name='decision-tree-confirm'>" + this.confirmLabel + "</button> </div>";
    };

    Task.prototype.choiceTemplate = function(choice, i) {
      return "<div>" + i + ": " + choice.label + " (" + choice.value + ")</div>";
    };

    function Task(options) {
      var key, value;
      if (options == null) {
        options = {};
      }
      for (key in options) {
        value = options[key];
        this[key] = value;
      }
      if (this.choices == null) {
        this.choices = [];
      }
      this.createRoot();
      this.hide();
    }

    Task.prototype.createRoot = function() {
      this.el = document.createElement('form');
      this.el.className = 'decision-tree-task';
      return this.el.setAttribute('data-task-type', this.type);
    };

    Task.prototype.renderTemplate = function() {
      return this.el.innerHTML = this.template();
    };

    Task.prototype.handleEvent = function(e) {
      var handler;
      handler = (function() {
        switch (e.type) {
          case 'submit':
            return this.handleSubmit;
        }
      }).call(this);
      return handler != null ? handler.call(this, e) : void 0;
    };

    Task.prototype.handleSubmit = function(e) {
      return e.preventDefault();
    };

    Task.prototype.reset = function() {
      return this.el.reset();
    };

    Task.prototype.enter = function() {
      this.show();
      return this.el.addEventListener('submit', this, false);
    };

    Task.prototype.exit = function() {
      this.el.removeEventListener('submit', this, false);
      return this.hide();
    };

    Task.prototype.getValue = function() {
      throw new Error("Define Task::getValue for " + this.type);
    };

    Task.prototype.getNext = function() {
      return this.next;
    };

    Task.prototype.show = function() {
      return this.el.style.display = '';
    };

    Task.prototype.hide = function() {
      return this.el.style.display = 'none';
    };

    return Task;

  })();

  DecisionTree = (function() {
    DecisionTree.tasks = {};

    DecisionTree.registerTask = function(taskClass) {
      return this.tasks[taskClass.prototype.type] = taskClass;
    };

    DecisionTree.prototype.CHANGE = 'decision-tree:change';

    DecisionTree.prototype.CONFIRM = 'decision-tree:confirm';

    DecisionTree.prototype.COMPLETE = 'decision-tree:complete';

    DecisionTree.prototype.tasks = null;

    DecisionTree.prototype.values = null;

    DecisionTree.prototype.currentTask = null;

    function DecisionTree(options) {
      var key, task, taskKey, value, _ref;
      if (options == null) {
        options = {};
      }
      for (key in options) {
        value = options[key];
        this[key] = value;
      }
      if (this.tasks == null) {
        this.tasks = {};
      }
      if (this.values == null) {
        this.values = {};
      }
      this.createRoot();
      _ref = this.tasks;
      for (taskKey in _ref) {
        task = _ref[taskKey];
        if (!(task instanceof Task)) {
          if (this.constructor.tasks[task.type] != null) {
            task = new this.constructor.tasks[task.type](task);
            this.tasks[taskKey] = task;
          } else {
            throw new Error("No registered task " + task.type);
          }
        }
        if (!task.key) {
          task.key = taskKey;
        }
        task.renderTemplate();
        this.el.appendChild(task.el);
      }
      this.el.addEventListener('change', this, false);
      this.el.addEventListener('submit', this, false);
    }

    DecisionTree.prototype.createRoot = function() {
      this.el = document.createElement('div');
      return this.el.className = 'decision-tree';
    };

    DecisionTree.prototype.handleEvent = function(e) {
      var handler;
      handler = (function() {
        switch (e.type) {
          case 'change':
            return this.handleChange;
          case 'submit':
            return this.handleSubmit;
        }
      }).call(this);
      return handler != null ? handler.call(this, e) : void 0;
    };

    DecisionTree.prototype.handleChange = function(e) {
      this.values[this.currentTask.key] = this.currentTask.getValue();
      return this.dispatchEvent(this.CHANGE, {
        key: this.currentTask.key,
        value: this.values[this.currentTask.key]
      });
    };

    DecisionTree.prototype.handleSubmit = function(e) {
      this.values[this.currentTask.key] = this.currentTask.getValue();
      this.dispatchEvent(this.CONFIRM, {
        key: this.currentTask.key,
        value: this.values[this.currentTask.key]
      });
      return this.loadTask(this.currentTask.getNext());
    };

    DecisionTree.prototype.loadTask = function(task) {
      var _ref;
      if ((_ref = this.currentTask) != null) {
        _ref.exit();
      }
      if (typeof task === 'function') {
        return this.loadTask(task(this));
      } else if (typeof task === 'string') {
        return this.loadTask(this.tasks[task]);
      } else if (task != null) {
        task.reset();
        delete this.values[task.key];
        this.dispatchEvent(this.CHANGE, {
          key: task.key,
          value: this.values[task.key]
        });
        task.enter();
        return this.currentTask = task;
      } else {
        return this.dispatchEvent(this.COMPLETE, {
          value: this.getValue()
        });
      }
    };

    DecisionTree.prototype.getValue = function() {
      return this.values;
    };

    DecisionTree.prototype.dispatchEvent = function(eventName, detail) {
      var e;
      if (+location.port > 1023) {
        if (typeof console !== "undefined" && console !== null) {
          console.log(this, eventName, detail);
        }
      }
      e = document.createEvent('CustomEvent');
      e.initCustomEvent(eventName, true, true, detail);
      return this.el.dispatchEvent(e);
    };

    return DecisionTree;

  })();

  DecisionTree.Task = Task;

  window.DecisionTree = DecisionTree;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = DecisionTree;
  }

}).call(this);
